Repository codersalman/Hacktoberfest-2022, pull requests merged in 2022-10, with the labels that each got.

#2 IOT/Arduino
  Arduino/8x8_led.ino
  Arduino/piano.ino
Labels: hacktoberfest-accepted, Appreciation 🚀✨, IOT / Arduino, beginner-friendly

#6 Basic Calculator using react
  React/calculator/package-lock.json
  React/calculator/package.json
  React/calculator/public/index.html
  React/calculator/src/App.js
  React/calculator/src/components/Button.js
  React/calculator/src/components/ButtonBox.js
  React/calculator/src/components/Screen.js
  React/calculator/src/components/Wrapper.js
  React/calculator/src/context/CalcContext.js
  React/calculator/src/index.css
  React/calculator/src/index.js
Labels: Appreciation 🚀✨, Javascript, ReactJS

#7 Registration_form
  Javascript/Registration_Form/Registration-template-master/Registration-template-master/README.md
  Javascript/Registration_Form/Registration-template-master/Registration-template-master/app.js
  Javascript/Registration_Form/Registration-template-master/Registration-template-master/index.html
  Javascript/Registration_Form/Registration-template-master/Registration-template-master/style.css
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly

#11 Added JavaScript Project
  Javascript/Random Number Generator/README.md
  Javascript/Random Number Generator/index.css
  Javascript/Random Number Generator/index.html
  Javascript/Random Number Generator/index.js
Labels: Appreciation 🚀✨, beginner-friendly

#9 Made a scientific calculator using HTML, CSS, JS.
  Javascript/Scientific_Calculator/bgimg3.jpg
  Javascript/Scientific_Calculator/calc.css
  Javascript/Scientific_Calculator/click.mp3
  Javascript/Scientific_Calculator/favicon.png
  Javascript/Scientific_Calculator/index.html
  Javascript/Scientific_Calculator/index.js
Labels: Appreciation 🚀✨, beginner-friendly

#14 Phone Directory
  Javascript/Phone Directory/README.md
  Javascript/Phone Directory/index.html
  Javascript/Phone Directory/phone.jpg
  Javascript/Phone Directory/script.js
  Javascript/Phone Directory/style.css
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly

#15 2 LEDs, 1 Switch
  Arduino/2led_1switch.ino
Labels: hacktoberfest-accepted, Appreciation 🚀✨, IOT / Arduino

#16 Calculator using javascript
  Javascript/Calculator/README.md
  Javascript/Calculator/bg.png
  Javascript/Calculator/index.css
  Javascript/Calculator/index.html
  Javascript/Calculator/string.js
Labels: Appreciation 🚀✨, Javascript, beginner-friendly

#17 Tic Tac Toe Game
  React/TIC_TAC_TOE Game/package-lock.json
  React/TIC_TAC_TOE Game/package.json
  React/TIC_TAC_TOE Game/public/favicon.ico
  React/TIC_TAC_TOE Game/public/index.html
  React/TIC_TAC_TOE Game/public/logo192.png
  React/TIC_TAC_TOE Game/public/logo512.png
  React/TIC_TAC_TOE Game/public/manifest.json
  React/TIC_TAC_TOE Game/public/robots.txt
  React/TIC_TAC_TOE Game/src/App.css
  React/TIC_TAC_TOE Game/src/App.js
  React/TIC_TAC_TOE Game/src/App.test.js
  React/TIC_TAC_TOE Game/src/Components/Board.js
  React/TIC_TAC_TOE Game/src/Components/Game.js
  React/TIC_TAC_TOE Game/src/Components/Square.js
  React/TIC_TAC_TOE Game/src/Winner.js
  React/TIC_TAC_TOE Game/src/index.css
  React/TIC_TAC_TOE Game/src/index.js
  React/TIC_TAC_TOE Game/src/logo.svg
  React/TIC_TAC_TOE Game/src/reportWebVitals.js
  React/TIC_TAC_TOE Game/src/setupTests.js
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, ReactJS

#18 added shut the box game
  Javascript/Shut the Box Game/.vscode/settings.json
  Javascript/Shut the Box Game/index.html
  Javascript/Shut the Box Game/script.js
  Javascript/Shut the Box Game/style.css
Labels: hacktoberfest-accepted, Javascript, beginner-friendly

#19 upload image to the aws using node and express js
  Javascript/File Upload to AWS/index.js
  Javascript/File Upload to AWS/package-lock.json
  Javascript/File Upload to AWS/package.json
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly, nodejs

#20 Arduino Traffic Light Simulator
  Arduino/arduino_traffic_light.ino
Labels: hacktoberfest-accepted, Appreciation 🚀✨, IOT / Arduino, beginner-friendly

#25 Create Obstacle_Avoider_Bot.ino
  Arduino/Obstacle_Avoider_Bot.ino
Labels: hacktoberfest-accepted, IOT / Arduino, beginner-friendly

#27 Line Follower Bot & Wifi Controlled Bot
  Arduino/Line_follower_Bot.ino
  Arduino/Wifi_Controlled_Bot.ino
Labels: IOT / Arduino, beginner-friendly

#29 Add GuessCode game to JavaScript folder
  Javascript/GuessCode/README.md
  Javascript/GuessCode/demo.png
  Javascript/GuessCode/index.html
  Javascript/GuessCode/js/common.js
  Javascript/GuessCode/js/jquery-3.5.1.js
  Javascript/GuessCode/js/main1.js
  Javascript/GuessCode/js/main2.js
  Javascript/GuessCode/levels/level1.html
  Javascript/GuessCode/levels/level2.html
  Javascript/GuessCode/styles/style.css
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly

#31 Created registration-page.php
  PHP/registration-page.php
Labels: hacktoberfest-accepted, Appreciation 🚀✨, PHP, beginner-friendly

#33 A simple ReactJS application
  React/DisplayData/README.md
  React/DisplayData/package-lock.json
  React/DisplayData/package.json
  React/DisplayData/public/index.html
  React/DisplayData/src/App.js
  React/DisplayData/src/DisplayData.js
  React/DisplayData/src/index.css
  React/DisplayData/src/index.js
Labels: hacktoberfest-accepted, Javascript, beginner-friendly, ReactJS

#38 Added GitHub DevFinder app to React folder
  React/github-app/README.md
  React/github-app/build/asset-manifest.json
  React/github-app/build/favicon.ico
  React/github-app/build/index.html
  React/github-app/build/logo192.png
  React/github-app/build/logo512.png
  React/github-app/build/manifest.json
  React/github-app/build/robots.txt
  React/github-app/build/static/css/main.c3bed0ca.css
  React/github-app/build/static/css/main.c3bed0ca.css.map
  React/github-app/build/static/js/main.71b4d6cb.js
  React/github-app/build/static/js/main.71b4d6cb.js.LICENSE.txt
  React/github-app/build/static/js/main.71b4d6cb.js.map
  React/github-app/package-lock.json
  React/github-app/package.json
  React/github-app/public/favicon.ico
  React/github-app/public/index.html
  React/github-app/public/logo192.png
  React/github-app/public/logo512.png
  React/github-app/public/manifest.json
  React/github-app/public/robots.txt
  React/github-app/src/App.css
  React/github-app/src/App.js
  React/github-app/src/App.test.js
  React/github-app/src/components/GithubCard.js
  React/github-app/src/index.js
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly, ReactJS

#37 scissors paper rock game
  Javascript/Scissors Paper Rock Game/READMe.md
  Javascript/Scissors Paper Rock Game/demo.gif
  Javascript/Scissors Paper Rock Game/img/cross.png
  Javascript/Scissors Paper Rock Game/img/paper.png
  Javascript/Scissors Paper Rock Game/img/rock.png
  Javascript/Scissors Paper Rock Game/img/scissors.png
  Javascript/Scissors Paper Rock Game/img/tick.png
  Javascript/Scissors Paper Rock Game/solutions/img/cross.png
  Javascript/Scissors Paper Rock Game/solutions/img/paper.png
  Javascript/Scissors Paper Rock Game/solutions/img/rock.png
  Javascript/Scissors Paper Rock Game/solutions/img/scissors.png
  Javascript/Scissors Paper Rock Game/solutions/img/tick.png
  Javascript/Scissors Paper Rock Game/solutions/index.css
  Javascript/Scissors Paper Rock Game/solutions/index.html
  Javascript/Scissors Paper Rock Game/solutions/index.js
Labels: hacktoberfest-accepted, Javascript, beginner-friendly, ReactJS

#54 adding new dev tolls
  dev-tools.md
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Devtool, beginner-friendly

#60 Refactored event listener
  Javascript/Calculator/index.css
  Javascript/Calculator/string.js
Labels: Appreciation 🚀✨, beginner-friendly

#50 Create Pratheeksha_loginpage
  Pratheeksha_loginpage
Labels: hacktoberfest-accepted, beginner-friendly

#63 Added to do list project
  Javascript/Todo Project/assets/css/list.css
  Javascript/Todo Project/assets/js/lib/jQuery.js
  Javascript/Todo Project/assets/js/list.js
  Javascript/Todo Project/list.html
Labels: hacktoberfest-accepted, Javascript, beginner-friendly

#66 Added File Upload using nodejs
  Javascript/nodejs-file-upload/index.js
  Javascript/nodejs-file-upload/package-lock.json
  Javascript/nodejs-file-upload/package.json
  Javascript/nodejs-file-upload/public/index.html
  Javascript/nodejs-file-upload/uploads/html
  Javascript/nodejs-file-upload/uploads/js
  Javascript/nodejs-file-upload/uploads/node
  Javascript/nodejs-file-upload/uploads/react
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly

#70 added the login function
  PHP/login.php
Labels: hacktoberfest-accepted, PHP, beginner-friendly

#78 Convert your PDF to Thumbnail img
  Javascript/Convert your PDF to Thumbnail - with PDFJS/Convert your PDF to Thumbnail img.html
Labels: hacktoberfest-accepted, Appreciation 🚀✨, beginner-friendly

#77 added airbnb data scrapper using nodejs and puppeteer
  Javascript/Airbnb_data_scrapper/Readme.md
  Javascript/Airbnb_data_scrapper/index.js
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript, beginner-friendly

#80 A program to Find body mass index
  Javascript/Bmi Calculator/BMI.html
  Javascript/Bmi Calculator/BMI.js
  Javascript/Bmi Calculator/Readme.md
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript

#81 rock paper and scissor game add in javascript project
  Javascript/Rock_Paper_&_Scissor_Game/index.html
  Javascript/Rock_Paper_&_Scissor_Game/index.js
  Javascript/Rock_Paper_&_Scissor_Game/style.css
Labels: hacktoberfest-accepted

#83 jsPDF with custom font
  Javascript/jsPDF with custom font.html
Labels: hacktoberfest-accepted, Appreciation 🚀✨

#88 Added a Ludo Dice android application project
  Android OR Flutter/MyLudoDice/.gitignore
  Android OR Flutter/MyLudoDice/.idea/.name
  Android OR Flutter/MyLudoDice/.idea/codeStyles/Project.xml
  Android OR Flutter/MyLudoDice/.idea/gradle.xml
  Android OR Flutter/MyLudoDice/.idea/misc.xml
  Android OR Flutter/MyLudoDice/.idea/runConfigurations.xml
  Android OR Flutter/MyLudoDice/app/.gitignore
  Android OR Flutter/MyLudoDice/app/build.gradle
  Android OR Flutter/MyLudoDice/app/debug/app-debug.apk
  Android OR Flutter/MyLudoDice/app/debug/output.json
  Android OR Flutter/MyLudoDice/app/proguard-rules.pro
  Android OR Flutter/MyLudoDice/app/release/app-release.apk
  Android OR Flutter/MyLudoDice/app/release/output.json
  Android OR Flutter/MyLudoDice/app/src/androidTest/java/com/example/myludodice/ExampleInstrumentedTest.java
  Android OR Flutter/MyLudoDice/app/src/main/AndroidManifest.xml
  Android OR Flutter/MyLudoDice/app/src/main/java/com/example/myludodice/MainActivity.java
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/dice1.png
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/dice2.png
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/dice3.png
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/dice4.png
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/dice5.png
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/dice6.png
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/drawable/ic_launcher_background.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/layout/activity_main.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-hdpi/ic_launcher.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-mdpi/ic_launcher.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  Android OR Flutter/MyLudoDice/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  Android OR Flutter/MyLudoDice/app/src/main/res/values/colors.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/values/strings.xml
  Android OR Flutter/MyLudoDice/app/src/main/res/values/styles.xml
  Android OR Flutter/MyLudoDice/app/src/test/java/com/example/myludodice/ExampleUnitTest.java
  Android OR Flutter/MyLudoDice/build.gradle
  Android OR Flutter/MyLudoDice/gradle.properties
  Android OR Flutter/MyLudoDice/gradle/wrapper/gradle-wrapper.jar
  Android OR Flutter/MyLudoDice/gradle/wrapper/gradle-wrapper.properties
  Android OR Flutter/MyLudoDice/gradlew
  Android OR Flutter/MyLudoDice/gradlew.bat
  Android OR Flutter/MyLudoDice/settings.gradle
Labels: hacktoberfest-accepted, Appreciation 🚀✨

#90 Analog Clock using Javascript ,Html and Css
  Javascript/Analog Clock/clock-1.png
  Javascript/Analog Clock/clock-2.jpg
  Javascript/Analog Clock/clock-3.png
  Javascript/Analog Clock/clock-4.jpg
  Javascript/Analog Clock/clock.png
  Javascript/Analog Clock/head.js
  Javascript/Analog Clock/index.htm
  Javascript/Analog Clock/style.css
Labels: hacktoberfest-accepted, Appreciation 🚀✨, beginner-friendly

#99 Fix calculator screen
  React/calculator/src/components/Screen.js
Labels: hacktoberfest-accepted, Appreciation 🚀✨, Javascript

#105 added login page
  Javascript/Login Page/index.html
  Javascript/Login Page/index.js
  Javascript/Login Page/login.js
  Javascript/Login Page/package-lock.json
  Javascript/Login Page/package.json
  Javascript/Login Page/postcss.config.js
  Javascript/Login Page/register.js
  Javascript/Login Page/style.css
  Javascript/Login Page/tailwind.config.js
Labels: Javascript

#109 React Search
  React/react_search.js
Labels: hacktoberfest-accepted, Appreciation 🚀✨, ReactJS

#107 Accordion using ReactJS 🪗
  React/Accordion/README.md
  React/Accordion/public/index.html
  React/Accordion/src/App.js
  React/Accordion/src/Question.js
  React/Accordion/src/accordion.css
  React/Accordion/src/data.js
  React/Accordion/src/index.js
  React/DisplayData/README.md
Labels: hacktoberfest-accepted, ReactJS

#123 drumkit added
  Drum Kit/images/crash.png
  Drum Kit/images/kick.png
  Drum Kit/images/snare.png
  Drum Kit/images/tom1.png
  Drum Kit/images/tom2.png
  Drum Kit/images/tom3.png
  Drum Kit/images/tom4.png
  Drum Kit/index.html
  Drum Kit/index.js
  Drum Kit/sounds/crash.mp3
  Drum Kit/sounds/kick-bass.mp3
  Drum Kit/sounds/snare.mp3
  Drum Kit/sounds/tom-1.mp3
  Drum Kit/sounds/tom-2.mp3
  Drum Kit/sounds/tom-3.mp3
  Drum Kit/sounds/tom-4.mp3
  Drum Kit/styles.css
Labels: hacktoberfest-accepted

#84 News Website in React JS
  React/news-app/.gitignore
  React/news-app/README.md
  React/news-app/android-chrome-192x192.png
  React/news-app/android-chrome-512x512.png
  React/news-app/apple-touch-icon.png
  React/news-app/asset-manifest.json
  React/news-app/favicon.ico
  React/news-app/images/favicon-16x16.png
  React/news-app/images/favicon-32x32.png
  React/news-app/images/logo.png
  React/news-app/index.html
  React/news-app/manifest.json
  React/news-app/package-lock.json
  React/news-app/package.json
  React/news-app/public/android-chrome-192x192.png
  React/news-app/public/android-chrome-512x512.png
  React/news-app/public/apple-touch-icon.png
  React/news-app/public/favicon.ico
  React/news-app/public/images/favicon-16x16.png
  React/news-app/public/images/favicon-32x32.png
  React/news-app/public/images/logo.png
  React/news-app/public/index.html
  React/news-app/public/manifest.json
  React/news-app/public/robots.txt
  React/news-app/robots.txt
  React/news-app/sampleOutput.json
  React/news-app/src/App.js
  React/news-app/src/App.test.js
  React/news-app/src/components/Navbar.css
  React/news-app/src/components/Navbar.js
  React/news-app/src/components/News.js
  React/news-app/src/components/NewsItem.js
  React/news-app/src/components/Spinner.js
  React/news-app/src/index.css
  React/news-app/src/index.js
  React/news-app/src/loader.gif
  React/news-app/src/reportWebVitals.js
  React/news-app/src/setupTests.js
Labels: enhancement, hacktoberfest-accepted, Appreciation 🚀✨, ReactJS

#125 Textutils website
  React/TextUtils/.gitignore
  React/TextUtils/package-lock.json
  React/TextUtils/package.json
  React/TextUtils/public/favicon-16x16.png
  React/TextUtils/public/favicon-32x32.png
  React/TextUtils/public/favicon-96x96.png
  React/TextUtils/public/favicon.ico
  React/TextUtils/public/index.html
  React/TextUtils/public/manifest.json
  React/TextUtils/public/robots.txt
  React/TextUtils/src/App.css
  React/TextUtils/src/App.js
  React/TextUtils/src/App.test.js
  React/TextUtils/src/components/Navbar.js
  React/TextUtils/src/components/TextForm.js
  React/TextUtils/src/index.css
  React/TextUtils/src/index.js
  React/TextUtils/src/reportWebVitals.js
  React/TextUtils/src/setupTests.js
Labels: hacktoberfest-accepted, Appreciation 🚀✨, ReactJS

#91 Create index.html
  Javascript/accordian_btn/index.html
Labels: hacktoberfest-accepted
